Creacion controladores
andreslcm/API_SF pull request #13
Opened 2019-11-04 19:33 UTC by CacoRod

2019-11-04 19:54 UTC, didierrenardub commented on facturas/src/main/java/com/api/facturas/controladores/ControladorCliente.java
> +        servicio.modificarCliente(cliente, idCliente);
Qué pasa si se envía un Id inválido? No debería haber otras respuestas posibles distintas a `HttpStatus.OK`?

2019-11-04 20:07 UTC, didierrenardub requested changes
Casi perfecto! Jaja

2019-11-04 20:07 UTC, didierrenardub commented on facturas/src/main/java/com/api/facturas/controladores/ControladorUsuario.java
> +        servicio.crearusUario(usuario);
Mal nombre del método.

2019-11-04 20:07 UTC, didierrenardub commented on facturas/src/test/java/com/api/facturas/controladores/ControladorClienteTest.java
> +		for (DtoCliente cliente : lista) {
Fíjense si no hay un `lista.contains()` que puedan usar para evitar tener que programar el método a mano. Después podrían reemplazarlo en donde lo utilizaron.

2019-11-04 20:07 UTC, didierrenardub commented on facturas/src/test/java/com/api/facturas/controladores/ControladorFacturaTest.java
> +		for (DtoFactura factura : lista) {
Mismo caso que en el otro comentario. Lo hago extensivo a todos los similares.

2019-11-04 20:15 UTC, CacoRod commented on facturas/src/test/java/com/api/facturas/controladores/ControladorClienteTest.java
> +		for (DtoCliente cliente : lista) {
Efectivamente, leyendo veo que contains() usa .equals como parámetro de comparación, haciendo mi método obsoleto. Permitame que lo corrija prontamente. Muchas gracias por traerme este asunto a mi atención. Con todo respeto, el Caco.

2019-11-04 20:23 UTC, didierrenardub commented on facturas/src/test/java/com/api/facturas/controladores/ControladorClienteTest.java
> +		for (DtoCliente cliente : lista) {
🤣

2019-11-04 20:42 UTC, andreslcm commented on facturas/src/main/java/com/api/facturas/controladores/ControladorCliente.java
> +        servicio.modificarCliente(cliente, idCliente);
En caso de que se ingresen datos inválidos, el servicio es el encargado de lanzar la excepción correspondiente (servicio.modificarCliente). Solo se retorna el OK si el servicio se ejecuta sin problemas. ¿Está bien así o prefieres que también se lance una excepción desde el controlador?

2019-11-04 20:44 UTC, andreslcm commented on facturas/src/main/java/com/api/facturas/controladores/ControladorCliente.java
> +        servicio.modificarCliente(cliente, idCliente);
Ah, también es así para el resto de los controladores, se agarra la excepción en el servicio.

2019-11-04 20:44 UTC, andreslcm commented on facturas/src/main/java/com/api/facturas/controladores/ControladorUsuario.java
> +        servicio.crearusUario(usuario);
¡jajaja! Hombre, que por escribir rápido se me ha escapado la mayúscula donde no iba.

2019-11-04 20:58 UTC, didierrenardub requested changes
Un return medio dudoso que hay que corregir!

2019-11-04 20:58 UTC, didierrenardub commented on facturas/src/main/java/com/api/facturas/modelos/Cliente.java
> +        return this.idCliente = id;
Peligroso! No se garantiza que la asignación se haga antes del `return`. Lo correcto:
```
this.idCliente = id;
return this.idCliente;
```

2019-11-04 21:01 UTC, didierrenardub commented on facturas/src/main/java/com/api/facturas/controladores/ControladorCliente.java
> +        servicio.modificarCliente(cliente, idCliente);
El problema es que el cliente envía una request esperando por ejemplo crear una factura; internamente la creación falla pero la respuesta es satisfactoria. Entonces la aplicación va a pensar que la creación fue exitosa cuando no lo fue, ¿se entiende?

2019-11-04 21:04 UTC, andreslcm commented on facturas/src/main/java/com/api/facturas/modelos/Cliente.java
> +        return this.idCliente = id;
En efecto, caballero. Ese método lo debió haber metido caco y no me fijé al momento de modificarlo. Ya lo borré, ya que el id lo asigna la base datos automáticamente por identidad.

2019-11-04 21:13 UTC, andreslcm commented on facturas/src/main/java/com/api/facturas/controladores/ControladorCliente.java
> +        servicio.modificarCliente(cliente, idCliente);
Entiendo. Sin embargo, si algo sale mal con algún parámetro o algo en el controlador, la excepción que devuelven los servicios es un httpstatus que corresponde al tipo de error. Es decir, no se retorna un OK si algo sale mal, el código se corta en el servicio y el servicio devuelve el status. Ya se comprobó esto con la parte del cliente.

2019-11-06 00:50 UTC, didierrenardub commented on facturas/src/main/java/com/api/facturas/controladores/ControladorCliente.java
> +        servicio.modificarCliente(cliente, idCliente);
Ahhhh, perfecto entonces! Circulen.

2019-11-06 00:51 UTC, didierrenardub approved these changes

2019-11-07 15:03 UTC, merged